# Copyright (c) 2024 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Build configuration for Apogee keyboard

---
include:
  - board: nice_nano//zmk
    shield: apogee
    snippet: zmk-usb-logging
